.github/ISSUE_TEMPLATE/story_template.md
.talismanrc
app/constants.py
app/providers/provider_aws.py
app/providers/provider_base.py
app/providers/utils.py
poetry.lock
pyproject.toml
tests/app/providers/test_provider_aws.py
tests/app/providers/test_provider_base.py

This PR enables retries for send notifications and push registration. Tenacity was used for retry functionality.
[Tenacity docs](https://tenacity.readthedocs.io/en/latest/index.html) are a little light on details, so extensive testing was required to ensure retries are working as expected.
issue #43 
Unit testing retries specifically was not something I have been able to accomplish yet. You could see retries happening in logs during unit testing and I performed extensive testing to verify retries are working as expected.

Enable Retries for Send Notification and Push Registration with Tenacity

---

.pre-commit-config.yaml
poetry.lock
tests/app/db/test_db_init.py

Updated dependencies.
Main app:
static_tools, test, mkdocks:
issue #105 
Compared pre/post outputs and they are consistent.

Updated dependencies and pre-commit

---

pyproject.toml
scripts/run_tests.sh

We have seen mistakes with Poetry versions a few times. This PR fixes that issue by enforcing a version in pyproject.toml that is checked in run_tests.sh
issue N/A
Works with [Github Actions](https://github.com/department-of-veterans-affairs/va-enp-api/actions/runs/12604063970/job/35130284246?pr=124#step:6:20).
Tested locally, works:

HOTFIX - Poetry Version Check

---

poetry.lock
pyproject.toml
tests/app/db/test_db_init.py
tests/app/legacy/v2/notifications/test_rest.py
tests/app/legacy/v2/notifications/test_utils.py
tests/app/providers/test_provider_aws.py
tests/app/providers/test_provider_base.py
tests/app/test_main.py

Updated all dependencies and turned asyncio_mode to auto (no need to mark tests).
issue N/A
Ran locally with no container, uvicorn and gunicorn. Ran with the local docker container. Everything is working as expected.

HOTFIX - Update Dependencies and Asyncio automode

---

app/legacy/v2/notifications/rest.py
app/legacy/v2/notifications/route_schema.py
app/main.py
tests/app/legacy/v2/notifications/test_rest.py

This PR adds POST routes for V2 SMS notifications. There are two endpoints:
- /legacy/v2/notifications/sms
- /v2/notifications/sms
Both endpoints are mapped to the same handler function.
issue #116 
- Tested locally with Swagger

#116 Notification routes with single handler

---

.github/pull_request_template.md
app/legacy/v2/notifications/rest.py
app/legacy/v2/notifications/route_schema.py
app/main.py
pyproject.toml
tests/app/test_main.py

Fixed the Keyboard Interrupt trace stack issue. Also saw we had two warnings reported from Pytest. Those were fixed and tests will no longer be able to pass with warnings. 
Fixes these warnings:
issue #128 
Fixed Pydantic Deprecation warning and swagger docs are still correct:

#128 - Fix for Keyboard Interrupt Issue

---

tests/app/test_main.py

Updated the two failing tests.
issue N/A

HOTFIX - Update Tests

---

.github/actions/build-push-artifacts/action.yml
.github/actions/ecs-task-render-deploy/action.yml
.github/workflows/deploy.yml
cd/va-enp-api-task-definition.json
scripts/wait_for_it.sh

This PR implements the following:
* Reusable GHA (composite) that builds and pushes the ENP Docker image to ECR
* Extends the ECS task rendering GHA (composite) to actually deploy the rendered task definition to a specified environment
* Extends the initial deploy workflow to call the above two actions to deploy ENP to an environment of choice
* Branch protection on PRs to enforce a successful deploy to dev before merging PRs
* Health check script for ECS container
issue #76 
Successful dev deployment here: https://github.com/department-of-veterans-affairs/va-enp-api/actions/runs/13016022043 with sha 9de97c45bc251f3221ae7d97d28b8af9c76c292c
Successful deployment banner in PR:
Successful image pull in task definition (using branch name):
Successful image push to ECR here (with both branch …

#76 - Implements deploy to environment workflow

---

.pre-commit-config.yaml
app/main.py
poetry.lock
tests/app/db/test_db_init.py
tests/app/providers/__init__.py
tests/app/providers/test_provider_aws.py

Just a routine update. 
- Had to change main.py method names because ruff thought they were unit tests. 
- All dependencies updated
- Fixed format errors
- Test that was failing output 4,700 lines, parameterized it.
issue N/A
Ran locally with and without the container. Functional.

HOTFIX - Update Dependencies

---

cd/va-enp-api-task-definition.json

This PR updates the datadog agent container to 7.62.1.
issue [#2250](https://github.com/department-of-veterans-affairs/notification-api/issues/2250#issue-2793749112)
This was already tested in API here: https://github.com/department-of-veterans-affairs/notification-api/pull/2287
There are no tasks running for ENP right now and there is nothing to verify in DD.

API-2250 -- Updates dd agent to 7.62.1

---

.github/actions/ecs-task-render-deploy/action.yml
.github/workflows/deploy.yml
.talismanrc

issue #159 
This pull request includes several changes to the GitHub Actions configuration files. The changes fix an issue with deploying the ENP and the environment file.
Improvements to GitHub Actions configuration:
* [`.github/actions/ecs-task-render-deploy/action.yml`](diffhunk://#diff-161e7f0cf42caf9608864ba93db36b02658943c12bb998f908d969daa57af0e4L14-R26): Updated the `inputs:` section to use double quotes for consistency and modified the `runs:` section to dynamically reference the environment variable in the S3 path. [[1]](diffhunk://#diff-161e7f0cf42caf9608864ba93db36b02658943c12bb998f908d969daa57af0e4L14-R26) [[2]](diffhunk://#diff-161e7f0cf42caf9608864ba93db36b02658943c12bb998f908d969daa57af0e4L48-R48)
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb …

HOTFIX #159 - Deploying ENP to Perf

---

.github/workflows/test_suite.yml
.talismanrc
ci/Dockerfile
poetry.lock
pyproject.toml

This PR upgrades Python to 3.13. Part of this ticket was upgrading dependencies, and botocore later than 1.3.620 caused a test failure.
issue #156 
- Unit tests pass, locally and in GHA - https://github.com/department-of-veterans-affairs/va-enp-api/actions/runs/13593020786/job/38003484246?pr=181

#156 - Upgrade Python to 3.13

---

.env.local
.talismanrc
app/db/db_init.py
app/main.py
ci/.env.docker
run_app_local.py

The ENP app needs to connect to a running API database, and an environment variable contains the connection URI.  This PR changes the API database host domain from "host.docker.internal", which only seems to exist by default on systems running Docker Desktop (i.e. Mac and Windows), to "ci-db-1" , which should resolve because all the running containers are in the "ci_default" network.  This should allow running the app locally with Docker on all systems.
The other changes are just updates to comments I read while figuring out how this works.  I also updated the ENP Wiki.
issue #125
I deployed the branch and asked a couple of people to make sure they can run the app locally with Docker using this branch.

#125 Docker configuration changes

---

.github/workflows/deploy.yml

This PR removes the unwieldy boolean logic from the secret string interpolation in our deploy workflow. It replaces it with interpolation that is automatically sourced from the environment input.
issue #187 
Deployed to both dev and perf and validated that the task definitions in each env had the correct secrets.

#187 - Fix secret json interpolation in deploy workflow

---

.talismanrc
poetry.lock

Updated dependencies.
issue N/A
Ran the app locally and verified the get notification route works with a notification object in the db.
Deployed and functioning correct as well:

Updated Dependencies

---

.github/workflows/test_suite.yml
ci/docker-compose-ci.yml

This PR does the following:
* Adds S3 commands to pull the notification-api schema from S3
* Creates a docker compose file containing postgres 15 and mounting the napi-schema.sql file into it for automatic seeding
issue #228 
https://github.com/department-of-veterans-affairs/va-enp-api/pull/232/commits/cd1fdf5c5061cfc5e4ffa1b28aad635eca3a2f47 added some logic in the workflow to dump the schema back to S3. The file is the same size as the original notification-api schema and the diff was minimal.

#228 - Imports notification-api schema into ENP CI workflow

---

app/db/db_init.py
app/legacy/dao/notifications_dao.py
tests/app/conftest.py
tests/app/db/test_db_init.py
tests/conftest.py

These changes create test fixtures for database access and update unit tests to connect to the database.  (Database connections are mocked in main.)
issue #171
It's all unit testing at this point.  We should do additional testing the first time somebody writes tests for a route to ensure that the rollback functionality works as intended.

#171 #225 Test database connections

---

.talismanrc
poetry.lock

Updated dependencies.
Changed talisman to ignore poetry.lock (hopefully)
issue N/A
Tested locally. [Deployed](https://github.com/department-of-veterans-affairs/va-enp-api/actions/runs/14714224142). Endpoints functional.

HOTFIX - Update Deps

---

.talismanrc
app/main.py
poetry.lock
tests/conftest.py

Updated dependencies. Hit the following trivial issues:
- Running locally with `python run_app_local.py` was broken, fixed it (trivial change).
- Teardown (pytest_sessionfinish) was using asyncio.run but that was ignoring the already running event loop. It has been modified to use the current loop.
- As a potential bonus: Corrected talisman scanning `poetry.lock`, hopefully.
issue N/A
Local testing is functional. Deployed, tested sending an SMS.

HOTFIX - Dependency Update

---

pyproject.toml
tests/app/legacy/dao/conftest.py
tests/app/legacy/dao/test_services.py

Updated to have 100% coverage when only testing:
`tests/app/legacy/dao/test_services_dao.py`
against
`/app/legacy/dao/services_dao.py`
issue #279 
See top and bottom of the image:

#279 - Update Tests to Cover LegacyServiceDao Class

---

.talismanrc
poetry.lock

issue #318 
This PR updates multiple Python dependencies to their latest versions to improve security, performance, and maintain compatibility with the latest changes.
**AWS/Boto3 Ecosystem:**
- `aiobotocore`: 2.22.0 → 2.23.0
- `boto3`: 1.37.3 → 1.38.27
- `botocore-stubs`: 1.38.30 → 1.38.46
- `types-aiobotocore`: 2.22.0 → 2.23.0 (all AWS service type stubs updated)
- `types-awscrt`: 0.27.2 → 0.27.4
**Web Framework & HTTP:**
- `aiohttp`: 3.12.12 → 3.12.13
- `fastapi`: 0.115.12 → 0.115.14
**Development & Testing Tools:**
- `pytest`: 8.4.0 → 8.4.1
- `pydantic`: 2.11.5 → 2.11.7
- `moto`: 5.1.5 → 5.1.6 (AWS service mocking)
**Utilities & Other Dependencies:**
- `phonenumbers`: 9.0.7 → 9.0.8
- `markdown`: 3.8 → 3.8.2
- `certifi`: 2025.4.26 → 2025.6.15 (updated certificate bundle)
- `cfn-lint`: …

#318 - upgrade dependencies

---

.github/workflows/deploy.yml
.github/workflows/pr_run_tests.yml
.github/workflows/test_suite.yml

This PR implements OIDC in our Github Actions workflows.
issue #365 
Successful deploy to dev using OIDC: https://github.com/department-of-veterans-affairs/va-enp-api/actions/runs/17269826085

#365 - Implement OIDC in Github Actions
